# When it can be done this easily (and stupidly) there's no reason not to have a makefile...
hurry:
	g++ -std=c++11 minibuss.cpp -o minibuss
	g++ -std=c++11 minibuss_no_inherit.cpp -o minibuss_noin
	g++ -std=c++11 protected.cpp -o protected
