GPP=g++ -std=c++11

all: templates1 templates2 mini

templates1:
	$(GPP) templates1.cpp -o templates1

templates2:
	$(GPP) templates2.cpp -o templates2

mini:
	$(GPP) -c template_mini.cpp


clean:
	$(RM) templates1 templates2 template_mini.o 
